# Site settings
title: Jekyll AWS Comments
description: Static Comments for Jekyll with AWS Lambda and GitHub
author: Michael Ummels
github_username: ummels

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

exclude: [node_modules, dist, dist.zip]
